#!/bin/bash

# This bash script is used to backup a user's home directory to a specified directory or drive.

if [[ "$1" = "--help" || "$1" = "-h" ]]; then
        printf "To use this program, just specify a directory to backup /home/$USER/ to."
        exit
fi

echo "Welcome to BACKUPHOMEv2."
echo "Where do you want to backup $USER's home directory?"
read choice

user=$(whoami)
input=/home/$user
output=/$choice/${user}_home_$(date +%Y-%m-%d_%H%M%S).tar.gz

echo "Starting backup..."

# The function total_files reports a total number of files for a given directory. 
function total_files {
        find $1 -type f | wc -l
}

# The function total_directories reports a total number of directories
# for a given directory. 
function total_directories {
        find $1 -type d | wc -l
}

tar -czf $output $input 2> /dev/null

echo -n "Files to be included:"
total_files $input
echo -n "Directories to be included:"
total_directories $input

echo "Backup of $input completed!"

echo "Details about the output backup file:"
ls -l $output]
