#!/bin/bash

# This bash script is used to backup a user's home directory to a specified directory or a different drive.
echo "Starting the backup..."

echo "Where do you want to back it up to?"
read choice
echo "Ok, backing up..."

user=$(whoami)
input=/home/$user
output=/$choice/${user}_home_$(date +%Y-%m-%d_%H%M%S).tar.gz

tar -czf $output $input
echo "Backup of $input completed! Details about the output backup file:"
ls -l $output
echo "Thank you for using this program."
